/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Admin' at '6/26/17 11:04 AM' with Gradle 3.0
 *
 * @author Admin, @date 6/26/17 11:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
